Order display cards + count on dashboard
DevelopmentHF/medpantry-itproject-57 pull request #27
Opened 2024-09-19 09:06 UTC by thanhlongnguyenn

2024-09-19 09:11 UTC, DevelopmentHF requested changes
Num orders on main dashboard page is still showing as 2. It should be 3.

<img width="364" alt="image" src="https://github.com/user-attachments/assets/9db25bcd-8525-4250-baf6-d6ccc24699bf">

2024-10-01 12:08 UTC, DevelopmentHF requested changes
Duplicated code Table 2 Table 3 ?

2024-10-01 12:08 UTC, DevelopmentHF commented on frontend/medpantry/components/Table 3.tsx
Why is this duplicated in the other files

2024-10-03 10:06 UTC, stakayanagi407 commented
Remade the Order into component. Please check

2024-10-03 10:59 UTC, DevelopmentHF approved these changes
Lgtm. Solid refactoring

2024-10-03 11:08 UTC, merged